# frozen_string_literal: true

source 'https://rubygems.org'

group :development do
  gem 'faraday'
  gem 'minitest', require: false
  gem 'rake', require: false
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
end
