# frozen_string_literal: true

require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.description = 'Run test for client'
  t.libs << 'test'
  t.test_files = FileList['test/**/test_*.rb']
end

Rake::TestTask.new(:scenario) do |t|
  t.description = 'Run scenarios for server'
  t.libs << 'scenario'
  t.test_files = FileList['scenario/**/test_*.rb']
end

task default: :test
